### ISSUE TITLE
Doesn't compile with Studio 3.4.x

### ISSUE THREAD

**Issue by kraghu** [palaima/DebugDrawer#97]
Hi there,
When I upgraded studio to latest 3.4.x and gradle to 5.x.x . it keeps throwing compilation error . Any workaround for this ?

**Comment by gjsalot** [comment]
I am also having this issue since upgrading to gradle plugin 3.4.0, gradle 5.1.1.

```
e: Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
    class io.palaima.debugdrawer.commons.BuildModule, unresolved supertypes: io.palaima.debugdrawer.base.DebugModuleAdapter
    class io.palaima.debugdrawer.actions.ActionsModule, unresolved supertypes: io.palaima.debugdrawer.base.DebugModule
    class io.palaima.debugdrawer.commons.DeviceModule, unresolved supertypes: io.palaima.debugdrawer.base.DebugModuleAdapter

```

**Comment by Nstd** [comment]
Maybe lost some dependency, such as `io.palaima.debugdrawer:debugdrawer-base:0.8.0`

**Comment by lenguyenthanh** [comment]
Adding `debugImplementation "io.palaima.debugdrawer:debugdrawer-base:$debugDrawer"` worked for me.

**Comment by omkar-tenkale** [comment]
`    debugImplementation "io.palaima.debugdrawer:debugdrawer-base:0.8.0"
`
